name: int-cicd
on:
  push:
    branches:
      - 'int'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'int'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/portal-oval:int
  deployment:
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: Prep helm chart
        run: |
          mv ./oval-chart/Chart.yaml ./oval-chart/Chart.old.yaml &&
          cat ./oval-chart/Chart.old.yaml | grep -v appVersion > ./oval-chart/Chart.yaml &&
          echo -e "\r\nappVersion: v${GITHUB_REF##*/}\r\n" >> ./oval-chart/Chart.yaml &&
          cat ./oval-chart/Chart.yaml
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade int-oval ./oval-chart --install --wait --atomic --namespace=int-oval --set=app.name=int_oval --values=./oval-chart/int-values.yaml
          kubeconfig: '${{ secrets.INT_KUBECONFIG }}'
